### ISSUE TITLE
Is this repo supposed to be compatible with npm-on-ipfs

### ISSUE THREAD

**Issue by AFDudley** [andrew/ipfs-npm-republish#12]
This doesn't seem to generate a registry like ipfs-npm-registry-mirror but maybe it could be used to refresh one? I'm trying to make an overlay style mirror (or whatever they call it in npm land).

**Comment by andrew** [comment]
@AFDudley this project makes small, static per-project registries which consist of just enough packages and packuments for a single javascript project (a few hundred usually) to install from directly from IPFS rather than to bootstrap a full registry.

**Comment by AFDudley** [comment]
Thanks. Can you please add example usage of the registry created to the readme?
