### ISSUE TITLE
Idea - add script to package.json for install from ipfs

### ISSUE THREAD

**Issue by jimpick** [andrew/ipfs-npm-republish#2]
As an alternative to creating a .npmrc file, which is potentially surprising, perhaps another alternative would be to have the tool optionally create a 'script' entry in package.json, eg:

```json
"scripts": {
    "install-ipfs": "npm install --registry=<cid>"
}
```

So people could run `npm install` to get the dependencies the normal way, or `npm run install-ipfs` to fetch via IPFS.

**Comment by andrew** [comment]
The only problem with this is that it suffers the same issue as `ipfs-npm` being a different binary, if it's not the default behavior then people will forget to use it, I'd prefer for this library to act as a "We're jumping to IPFS" switch rather than an option.

**Comment by stagedataloss** [comment]
test123
